### PR TITLE
try to proper redirect download

### PR DESCRIPTION
**Pull request by ebarboni**
trying to fix the https://github.com/apache/netbeans/issues/7224 serverside

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Well, it'll work - does redirect twice. `/download => /front/main/download => /front/main/download/`

I'm not sure there's an easy way around that without doing something more complex with rewrite rules?

Should consider whether the other links should work correctly without a trailing slash too - eg. https://netbeans.apache.org/blogs

**Review by neilcsmith-net — APPROVED** [review]

**Comment by ebarboni** [comment]
more changes for blog and issue from ide branding  resources

**Review by mbien — APPROVED** [review]
this looks like it would fix the problem of the 404s, but do we redirect into the right direction?

https://netbeans.apache.org/download/nb21/
looks nicer than
https://netbeans.apache.org/front/main/download/nb21/
which exposes impl details.

But I guess that is how antora works?

**Comment by ebarboni** [comment]
I will let that in. url may be complex but better than 404

**Pull request merged**
